export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const CONTACT_INPUT_VALUE_CHANGED = 'CONTACT_INPUT_VALUE_CHANGED';
export const EDIT_CONTACT = "EDIT_CONTACT";
